package com.aseuro.pms.model;

public enum PMSState {
    PMS_NOT_STARTED,
    PMS_STARTED,
    SELF_ASSESSMENT_DRAFT,
    SELF_ASSESSMENT_SUBMITTED,
    MANAGER_REVIEW_PENDING,
    MANAGER_REVIEW_SUBMITTED,
    HR_REVIEW_PENDING,
    HR_REVIEW_COMPLETED,
    RATING_AND_POINTS_CALCULATED,
    FINAL_ANALYSIS,
    FINAL_RESULT_PUBLISHED,
    COMPLETED
}
