package com.company.pms;

import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class DataInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbc;
    private final PasswordEncoder encoder;

    public DataInitializer(JdbcTemplate jdbc, PasswordEncoder encoder) {
        this.jdbc = jdbc;
        this.encoder = encoder;
    }

    @Override
    public void run(String... args) throws Exception {
        jdbc.execute("CREATE TABLE IF NOT EXISTS users (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "username VARCHAR(100) NOT NULL, " +
                "email VARCHAR(150) NOT NULL UNIQUE, " +
                "password_hash VARCHAR(255) NOT NULL, " +
                "role VARCHAR(20) NOT NULL, " +
                "status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', " +
                "last_login_at TIMESTAMP)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS departments (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(100) NOT NULL, " +
                "description VARCHAR(255), " +
                "status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS teams (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "department_id BIGINT NOT NULL, " +
                "name VARCHAR(100) NOT NULL, " +
                "description VARCHAR(255), " +
                "status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS designations (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "name VARCHAR(100) NOT NULL, " +
                "description VARCHAR(255), " +
                "status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS employees (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "user_id BIGINT, " +
                "employee_code VARCHAR(50) NOT NULL UNIQUE, " +
                "full_name VARCHAR(150) NOT NULL, " +
                "email VARCHAR(150) NOT NULL UNIQUE, " +
                "department_id BIGINT, " +
                "team_id BIGINT, " +
                "designation_id BIGINT, " +
                "manager_id BIGINT, " +
                "joining_date DATE, " +
                "status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', " +
                "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS kpis (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "designation_id BIGINT, " +
                "kpi_name VARCHAR(255) NOT NULL, " +
                "measurement_percent DOUBLE PRECISION NOT NULL, " +
                "self_rating_default DOUBLE PRECISION DEFAULT 5.0, " +
                "manager_rating_default DOUBLE PRECISION DEFAULT 4.0, " +
                "description TEXT)");

        jdbc.execute("CREATE TABLE IF NOT EXISTS pms_evaluations (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "employee_id BIGINT NOT NULL, " +
                "kpi_id BIGINT NOT NULL, " +
                "self_rating DOUBLE PRECISION, " +
                "manager_rating DOUBLE PRECISION, " +
                "hr_rating DOUBLE PRECISION, " +
                "evaluation_month VARCHAR(20), " +
                "status VARCHAR(50) DEFAULT 'DRAFT', " +
                "finalized_at TIMESTAMP)");

        // Seed default Users
        Integer userCount = jdbc.queryForObject("SELECT COUNT(*) FROM users", Integer.class);
        if (userCount == null || userCount == 0) {
            String hash = encoder.encode("Password123!");
            jdbc.update("INSERT INTO users (id, username, email, password_hash, role, status) VALUES (1, ?, ?, ?, ?, ?)",
                    "hr.demo", "hr.demo@company.com", hash, "HR", "ACTIVE");
            jdbc.update("INSERT INTO users (id, username, email, password_hash, role, status) VALUES (2, ?, ?, ?, ?, ?)",
                    "manager.demo", "manager.demo@company.com", hash, "MANAGER", "ACTIVE");
            jdbc.update("INSERT INTO users (id, username, email, password_hash, role, status) VALUES (3, ?, ?, ?, ?, ?)",
                    "employee.demo", "employee.demo@company.com", hash, "EMPLOYEE", "ACTIVE");
        }

        // Seed Departments
        Integer deptCount = jdbc.queryForObject("SELECT COUNT(*) FROM departments", Integer.class);
        if (deptCount == null || deptCount == 0) {
            jdbc.update("INSERT INTO departments (id, name, description, status) VALUES (1, 'Engineering', 'Software Development & IT', 'ACTIVE')");
            jdbc.update("INSERT INTO departments (id, name, description, status) VALUES (2, 'Human Resources', 'HR & Operations', 'ACTIVE')");
            jdbc.update("INSERT INTO departments (id, name, description, status) VALUES (3, 'Finance', 'Finance & Accounting', 'ACTIVE')");
        }

        // Seed Teams
        Integer teamCount = jdbc.queryForObject("SELECT COUNT(*) FROM teams", Integer.class);
        if (teamCount == null || teamCount == 0) {
            jdbc.update("INSERT INTO teams (id, department_id, name, description, status) VALUES (1, 1, 'Frontend Team', 'React & Web UI', 'ACTIVE')");
            jdbc.update("INSERT INTO teams (id, department_id, name, description, status) VALUES (2, 1, 'Backend Team', 'Java Spring Services', 'ACTIVE')");
            jdbc.update("INSERT INTO teams (id, department_id, name, description, status) VALUES (3, 2, 'HR Ops', 'Talent & Onboarding', 'ACTIVE')");
        }

        // Seed Designations
        Integer desigCount = jdbc.queryForObject("SELECT COUNT(*) FROM designations", Integer.class);
        if (desigCount == null || desigCount == 0) {
            jdbc.update("INSERT INTO designations (id, name, description, status) VALUES (1, 'Software Engineer', 'Core IC role', 'ACTIVE')");
            jdbc.update("INSERT INTO designations (id, name, description, status) VALUES (2, 'Engineering Manager', 'People & Tech Manager', 'ACTIVE')");
            jdbc.update("INSERT INTO designations (id, name, description, status) VALUES (3, 'HR Specialist', 'HR Operations', 'ACTIVE')");
        }

        // Seed Employees
        Integer empCount = jdbc.queryForObject("SELECT COUNT(*) FROM employees", Integer.class);
        if (empCount == null || empCount == 0) {
            jdbc.update("INSERT INTO employees (id, user_id, employee_code, full_name, email, department_id, team_id, designation_id, status) VALUES (1, 2, 'MGR001', 'Jane Manager', 'manager.demo@company.com', 1, 2, 2, 'ACTIVE')");
            jdbc.update("INSERT INTO employees (id, user_id, employee_code, full_name, email, department_id, team_id, designation_id, manager_id, status) VALUES (2, 3, 'EMP002', 'John Employee', 'employee.demo@company.com', 1, 1, 1, 1, 'ACTIVE')");
        }

        // Seed 12 Default KPIs (FRD Image 2) for Software Engineer (id=1)
        Integer kpiCount = jdbc.queryForObject("SELECT COUNT(*) FROM kpis", Integer.class);
        if (kpiCount == null || kpiCount == 0) {
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Sprint Task Completion - tasks completed within sprint (individual)', 10, 5, 4)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Deadline Adherence - tasks completed on or before deadline', 15, 5, 4)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Task Quality with Defects - tasks delivered without defects, including reopen and critical issues', 10, 5, 3)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Prompt Quality - AI tasks with minimal rework', 15, 5, 2)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Jira Time Logging - days logged properly in Jira', 10, 5, 4)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Jira Discipline - status updates, comments, transitions, and ticket hygiene', 5, 5, 2)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Accountability & Ownership - proactive ownership, updates, issue handling, team collaboration', 10, 5, 2)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Leave Pattern - planned leaves should be 95% of total leaves; unplanned leaves should not exceed 5%', 5, 5, 4)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Team Collaboration and Engagement', 5, 5, 2)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Punctuality', 5, 4, 2)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'New Initiatives and Participation', 5, 5, 3)");
            jdbc.update("INSERT INTO kpis (designation_id, kpi_name, measurement_percent, self_rating_default, manager_rating_default) VALUES (1, 'Rewards', 5, 5, 0)");
        }

        // Restart identity sequences at 20 so JPA generated keys never collide
        try {
            jdbc.execute("SELECT setval(pg_get_serial_sequence('users', 'id'), 20, false)");
            jdbc.execute("SELECT setval(pg_get_serial_sequence('employees', 'id'), 20, false)");
            jdbc.execute("SELECT setval(pg_get_serial_sequence('departments', 'id'), 20, false)");
            jdbc.execute("SELECT setval(pg_get_serial_sequence('teams', 'id'), 20, false)");
            jdbc.execute("SELECT setval(pg_get_serial_sequence('designations', 'id'), 20, false)");
            jdbc.execute("SELECT setval(pg_get_serial_sequence('kpis', 'id'), 20, false)");
        } catch (Exception e) {
            try {
                jdbc.execute("ALTER TABLE users ALTER COLUMN id RESTART WITH 20");
                jdbc.execute("ALTER TABLE employees ALTER COLUMN id RESTART WITH 20");
                jdbc.execute("ALTER TABLE departments ALTER COLUMN id RESTART WITH 20");
                jdbc.execute("ALTER TABLE teams ALTER COLUMN id RESTART WITH 20");
                jdbc.execute("ALTER TABLE designations ALTER COLUMN id RESTART WITH 20");
                jdbc.execute("ALTER TABLE kpis ALTER COLUMN id RESTART WITH 20");
            } catch (Exception ignored) {}
        }
    }
}
