spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:${DB_URL}}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}

server:
  address: 0.0.0.0
  port: ${PORT:8085}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

  frontend-url: ${PMS_FRONTEND_URL:http://localhost:5173}

brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: ${BREVO_SENDER_EMAIL}
  sender-name: ${BREVO_SENDER_NAME:Aseuro PMS}